### ISSUE TITLE
Issue with jewelry icons

### ISSUE THREAD

**Issue by kempxa** [Baertram/ResearchAssistant#8]
1. I bought an Exemplary Swift Necklace and two Exemplary Swift Rings for research
2. I can currently only do one jewelry research at a time on my character, so I started with the ring stated above. Note, that I accidentally bought two rings of the same kind, so now I have the necklace and a spare ring in my inventory
3. In my inventory, the "researchable" icon is shown on the ring and **not on the necklace**

![Screenshot_20240810_190047](https://github.com/user-attachments/assets/cdadc4dd-4a3f-4265-aa60-2ec9c7789ccb)
![Screenshot_20240810_190058](https://github.com/user-attachments/assets/9dae07ea-d754-4833-9086-c905e7a915d1)
![Screenshot_20240810_190109](https://github.com/user-attachments/assets/40b9be1b-2e37-4c6e-b280-9b9344b55ba6)

The only other addon I'm currently using is Perfect Pixel and I already tried to turn it off to see, if the bug went away. Thank you for looking into this!

**Comment by Baertram** [comment]
Did you update RA as I had fixed that error with lates update a few weeks ago afaik?

**Comment by kempxa** [comment]
I just downloaded and installed the Addon through Minion and it shows that the last update happened on August 2023. So are you saying I should install the Addon manually?

**Comment by Baertram** [comment]
Sorry, updated my post above.
I had forgotten to update it as I needed feedback :)

**Comment by kempxa** [comment]
Thanks for the clarification. I downloaded the addon through your link and at least now the researchable icon is being shown correctly on the necklace. I already sold the duplicate ring, so can't confirm anything on that.

**Comment by Baertram** [comment]
Okay thanks, will update the library now and in case you see any other issues just contact me here or on esoui.com.

Thanks for "the reminder" to update teh library ;-)

**Comment by kempxa** [comment]
Thanks for the help and for the great addon!
